### ISSUE TITLE
 Black accents when quote is visible in the right sidebar

### ISSUE THREAD

**Issue by danieltomasz** [sethfair/logseq-atlas-theme#2]
A really great theme!

After updating the theme today quotes became black
-  ![image](https://user-images.githubusercontent.com/7980381/141646988-38487468-e3c0-4e67-984c-1c68b91a38cf.png)

I have the feeling that the quotes were displayed differently earlier. Is this a design choice or a bug?

**Comment by sethfair** [comment]
@danieltomasz hi, thanks for the feedback.  No definitely not by design.  Do you have any overrides in your custom.css file?  What version of logseq are you on?  Are you on a mac or pc?

**Comment by danieltomasz** [comment]
I am on Logseq 0.4.6 (the preview version), MacOS BigSur 11.6
I checked some dark themes today, to reproduce you might try to install D42ker theme, switch to it and switch back to Atlas
I tried to uninstall every theme and reinstall Atlas but the behaviour persist

the dark quote appear only when the note is opened  in the right sidebar, in the main panel is ok
When I use default theme, the right panel is ok. when I switch to Atlas quote become black (it uses different css than quote in main panel I think)
![image](https://user-images.githubusercontent.com/7980381/141650307-4cc3e9ed-b65a-4792-a5a9-f2586ac90225.png)

custom.css is blank

**Comment by sethfair** [comment]
@danieltomasz I have made an update to the theme in v0.1.3 to fix this.  Hopefully this fixes it on your side.  It should look like the following:

![blockquote](https://user-images.githubusercontent.com/3271366/141653293-feb18ee2-f2c0-439e-b5fb-b2fd73cccfc5.png)

**Comment by danieltomasz** [comment]
After  updating theme and restarting the app it works! thank you for such fast response!
