### ISSUE TITLE
Dark mode unreadable inline code

### ISSUE THREAD

**Issue by Bad3r** [sethfair/logseq-atlas-theme#3]
In the new dark mode, inline code became unreadable. 
![image](https://user-images.githubusercontent.com/25513724/142757726-1b2da022-3ace-4133-a3d1-84315f94a0e9.png)

**Comment by sethfair** [comment]
@Bad3r , I have updated the theme with a fix to the blockquote.  Can you please update to 0.2.12 and check if this fixes the issue?  I did not see an issue with the inline code using the backtick.  Only when I used `> test`

**Comment by Bad3r** [comment]
@sethfair I updated the theme and the issue is not fixed.

I am using backtick for `inline code`

**Comment by sethfair** [comment]
Can you confirm the logseq version, atlas theme version as well as your OS version?  Also please check that you do not have any styles in your custom.css that would override this.  Are you using the theme as a plugin?

When running my theme, I see it as the following using your text as a sample
![backtick](https://user-images.githubusercontent.com/3271366/142794957-6c7b8a84-2cfc-4ba2-a2da-a43519167098.gif)
.

**Comment by Bad3r** [comment]
I didn't have a `custom.css` file, but I tried clearing logseq cache from the settings and that solved the issue.

Thank you for your help
